apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

bases:
  - ../../base

namePrefix: dev-
nameSuffix: -v1

commonLabels:
  environment: development
  team: dev-team

replicas:
  - name: demo-app
    count: 1

images:
  - name: demo-app
    newTag: dev-latest

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: demo-app-config
    behavior: merge
    literals:
      - environment=development
      - log-level=debug
      - feature-flags=experimental-features-enabled

resources:
  - ingress.yaml