source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'json', '~> 2.6'
gem 'rack', '~> 3.0'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.0'
  gem 'simplecov', '~> 0.22'
  gem 'rubocop', '~> 1.50'
end